name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: selene ./src
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.5.0"
      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.1"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Wally Packages
        run: |
          mv ./wally.toml ./src
          cd src
          wally install
      - name: Install & Run Darklua
        run: |
          cargo install --git https://gitlab.com/seaofvoices/darklua.git#v0.6.0
          darklua process src/ src/ --format retain-lines
      - name: Install Dependencies
        run: |
          luarocks install luafilesystem
      - name: Test
        run: lua tester/lemur.lua